### ISSUE TITLE
Integration with Translator wiki pages via simple hyperlinks

### ISSUE THREAD

**Issue by karafecho** [NCATSTranslator/TranslatorTechnicalDocumentation#48]
@vemonet had suggested that we migrate the Translator wiki pages to the Developer Documentation website. However, this will present complications as: (1) NCATS hosts the wiki pages and so any change will require their permission; (2) the InfoRes Catalog includes URLs for the wiki pages and so any change in the wiki page locations will require approval from the Biolink team and (manual) updates to the InfoRes Catalog; and (3) the UI pulls the URLs from the InfoRes Catalog for display to users for aid in edge interpretation and so any change in the wiki page locations or the approach we are using to expose the wiki pages will require approval from the UI team. See  https://github.com/NCATSTranslator/translator-developer-documentation/issues/28. 

Instead, I propose that the Developer Documentation includes links to [wiki pages](https://github.com/NCATSTranslator/Translator-All/wiki) for Translator components such as the ARAs and KPs, rather than separate pages for each ARA and KP, which as Vincent points out, will require a duplication of effort and likely will result in discrepancies in documentation for a given resource. The KP page already contains a table with a partial listing of KPs and their wiki pages, so something similar could be created for the ARA page. Then, the separate pages for individual components (ARAX, RTX-KG2, Service Provider) could be deleted. This would clean things up a bit, in my opinion.

**Comment by vemonet** [comment]
Thanks for the details @karafecho, indeed moving completely the wiki pages would be a lot of work without much actual benefits 

Just having one page for the **Teams** in the Developer documentation with the links to the teams wiki pages would be the best solution

Note that the [index of the wiki](https://github.com/NCATSTranslator/Translator-All/wiki) also provided tables of all teams with links: KPs, ARAs, SRI

**Comment by RichardBruskiewich** [comment]
The landing page of the Wiki is now the official "team" information page. The main entry point from the tech docs site is via a highlighted link inside the Welcome overview page.
