### ISSUE TITLE
Fill out "Systems Design" component of the documentation

### ISSUE THREAD

**Issue by RichardBruskiewich** [NCATSTranslator/TranslatorTechnicalDocumentation#7]
[Systems Design](https://github.com/NCATSTranslator/translator-developer-documentation/blob/main/docs/architecture/index.md#system-design-overview)

in the https://github.com/NCATSTranslator/translator-developer-documentation/blob/master/docs/architecture/index.md#system-design-overview section

**Comment by tursynay** [comment]
Hi @putmantime, following up about this issue. Would you like a meeting/discussion with some of the sri folks to get a first draft on this?
