### ISSUE TITLE
Predicate not complete

### ISSUE THREAD

**Issue by dkoslicki** [NCATSTranslator/TranslatorTechnicalDocumentation#77]
https://github.com/NCATSTranslator/TranslatorTechnicalDocumentation/blob/e006d5106916be105327ea5cd7d1bab180ba1ddb/docs/development-guide/HelloTranslator.ipynb#L55

The predicate on this line doesn't appear to be complete, so likely will throw an error when actually running it

**Comment by dkoslicki** [comment]
Also, please note that the arax.ncats.io URL base should be replaced with arax.transltr.io

**Comment by RichardBruskiewich** [comment]
Resolved by commit #c6cc7574c2
