### ISSUE TITLE
Self referential link?

### ISSUE THREAD

**Issue by dkoslicki** [NCATSTranslator/TranslatorTechnicalDocumentation#84]
https://github.com/NCATSTranslator/TranslatorTechnicalDocumentation/blob/e006d5106916be105327ea5cd7d1bab180ba1ddb/docs/development-guide/index.md?plain=1#L20

It appears that the "Architecture overview page" link just directs to the page that link is on. Was it intended that it link somewhere else?

**Comment by RichardBruskiewich** [comment]
Resolved by commit #ca63516c5c
